logging:
  level:
    ROOT: INFO
    ru.tversu.apka: INFO
  file:
    name: /usr/share/app/logs/app.log
  pattern:
    file: "%boldGreen(%d{yyyy-MM-dd}) | %boldBlue(%d{HH:mm:ss.SSS}) | %highlight(%-5level) | %cyan(%-20.20thread) | %-25.25logger{25} | %-25.25method{25}  | %m%xEx{full}%n"


spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgres.backend:5432/apka
    username: apka
    password: apka
    name: apka-prod-database
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 10
      max-lifetime: 600000
      driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    contexts: prod
  mail:
    host: localhost
    port: 25
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.query.plan_parameter_metadata_max_size: 2000
      hibernate.query.plan_cache_max_size: 20000
      hibernate.hbm2ddl.auto: validate
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  tomcat:
    max-connections: 20000
    threads:
      min-spare: 20
      max: 400

# ===================================================================
# Application specific properties
# ===================================================================

application:
  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461
  cors:
    #    allowed-origins: 'http://localhost:8080,http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000'
    allowed-origins: '*'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Link,X-Total-Count,X-${application.clientApp.name}-alert,X-${application.clientApp.name}-error,X-${application.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    remember-me:
      # security key (this key should be unique for your application, and kept secret)
      key: 244dcd52fe6a27770d6eeb33b8abbffbf065ad5ad915225707750da43df8f7c583b8eb6133a55264ab881e91d9580369ed01
  mail:
    base-url: http://my-server-url-to-change # Modify according to your server's URL
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
